// <auto-generated />
using System;
using DataAccessObjects;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccessObjects.Migrations
{
    [DbContext(typeof(CarShowroomContext))]
    [Migration("20260624073012_SyncModelWithContext")]
    partial class SyncModelWithContext
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BusinessObjects.Models.AppRole", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId")
                        .HasName("PK__AppRoles__8AFACE1ABED980DF");

                    b.HasIndex(new[] { "RoleName" }, "UQ__AppRoles__8A2B6160E1219BDE")
                        .IsUnique();

                    b.ToTable("AppRoles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            RoleName = "Customer"
                        });
                });

            modelBuilder.Entity("BusinessObjects.Models.AppUser", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("CodeExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("VerificationCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId")
                        .HasName("PK__AppUsers__1788CC4CD3D16938");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "Email" }, "UQ__AppUsers__A9D10534CD643903")
                        .IsUnique();

                    b.ToTable("AppUsers");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Address = "Hanoi",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@gmail.com",
                            FullName = "System Admin",
                            IsActive = true,
                            PasswordHash = "$2a$11$ivuFcskipHfVJyUk7X7Cy.72DYWJAKQhFt7uaF2kMrwZ/LAHW1cWO",
                            PhoneNumber = "0987654321",
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 2,
                            Address = "HCM City",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "customer@gmail.com",
                            FullName = "John Customer",
                            IsActive = true,
                            PasswordHash = "$2a$11$iR0JU.l1mLeRCyKuClJFxuWqtweaw2kS3oZSRG/lAcD00M603P5Mm",
                            PhoneNumber = "0123456789",
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("BusinessObjects.Models.Car", b =>
                {
                    b.Property<int>("CarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CarId"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<string>("CarName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Mileage")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Available");

                    b.Property<string>("Transmission")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("CarId")
                        .HasName("PK__Cars__68A0342E9C46E9E9");

                    b.HasIndex("BrandId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            CarId = 1,
                            BrandId = 1,
                            CarName = "Toyota Camry 2.5Q",
                            Color = "Black",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Xe sang trọng, lịch lãm, gia đình sử dụng kỹ, bảo dưỡng chính hãng.",
                            FuelType = "Gasoline",
                            ImageUrl = "https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?auto=format&fit=crop&w=600&q=80",
                            Mileage = 15000,
                            Model = "Camry",
                            Price = 1350000000m,
                            Status = "Available",
                            Transmission = "Automatic",
                            Year = 2022
                        },
                        new
                        {
                            CarId = 2,
                            BrandId = 1,
                            CarName = "Toyota Vios 1.5G",
                            Color = "White",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Xe quốc dân tiết kiệm nhiên liệu, vận hành bền bỉ.",
                            FuelType = "Gasoline",
                            ImageUrl = "https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?auto=format&fit=crop&w=600&q=80",
                            Mileage = 28000,
                            Model = "Vios",
                            Price = 520000000m,
                            Status = "Available",
                            Transmission = "Automatic",
                            Year = 2021
                        },
                        new
                        {
                            CarId = 3,
                            BrandId = 2,
                            CarName = "Ford Ranger Wildtrak 2.0L",
                            Color = "Orange",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Vua bán tải, phiên bản cao cấp nhất Wildtrak 2 cầu, đầy đủ công nghệ.",
                            FuelType = "Diesel",
                            ImageUrl = "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=600&q=80",
                            Mileage = 8000,
                            Model = "Ranger",
                            Price = 960000000m,
                            Status = "Available",
                            Transmission = "Automatic",
                            Year = 2023
                        },
                        new
                        {
                            CarId = 4,
                            BrandId = 3,
                            CarName = "VinFast VF8 Plus",
                            Color = "Blue",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Xe điện thông minh Việt Nam, bản Plus pin SDI, công nghệ ADAS hiện đại.",
                            FuelType = "Electric",
                            ImageUrl = "https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&w=600&q=80",
                            Mileage = 5000,
                            Model = "VF8",
                            Price = 1100000000m,
                            Status = "Available",
                            Transmission = "Automatic",
                            Year = 2023
                        },
                        new
                        {
                            CarId = 5,
                            BrandId = 4,
                            CarName = "BMW 320i Sport Line",
                            Color = "Red",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Dòng sedan thể thao lái cực hay, ngoại hình trẻ trung năng động.",
                            FuelType = "Gasoline",
                            ImageUrl = "https://images.unsplash.com/photo-1555215695-3004980ad54e?auto=format&fit=crop&w=600&q=80",
                            Mileage = 35000,
                            Model = "3 Series",
                            Price = 1250000000m,
                            Status = "Available",
                            Transmission = "Automatic",
                            Year = 2020
                        },
                        new
                        {
                            CarId = 6,
                            BrandId = 3,
                            CarName = "VinFast VF5 Plus",
                            Color = "Gray",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Xe đô thị cỡ nhỏ thông minh, cực kỳ tiết kiệm và nhỏ gọn.",
                            FuelType = "Electric",
                            ImageUrl = "https://images.unsplash.com/photo-1617788138017-80ad40651399?auto=format&fit=crop&w=600&q=80",
                            Mileage = 2000,
                            Model = "VF5",
                            Price = 450000000m,
                            Status = "Available",
                            Transmission = "Automatic",
                            Year = 2023
                        });
                });

            modelBuilder.Entity("BusinessObjects.Models.CarBrand", b =>
                {
                    b.Property<int>("BrandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BrandId"));

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("BrandId")
                        .HasName("PK__CarBrand__DAD4F05EFE11BDE9");

                    b.ToTable("CarBrands");

                    b.HasData(
                        new
                        {
                            BrandId = 1,
                            BrandName = "Toyota",
                            Country = "Japan",
                            Description = "Toyota Motor Corporation"
                        },
                        new
                        {
                            BrandId = 2,
                            BrandName = "Ford",
                            Country = "USA",
                            Description = "Ford Motor Company"
                        },
                        new
                        {
                            BrandId = 3,
                            BrandName = "VinFast",
                            Country = "Vietnam",
                            Description = "VinFast Vietnam"
                        },
                        new
                        {
                            BrandId = 4,
                            BrandName = "BMW",
                            Country = "Germany",
                            Description = "Bayerische Motoren Werke AG"
                        });
                });

            modelBuilder.Entity("BusinessObjects.Models.DepositCaptcha", b =>
                {
                    b.Property<int>("CaptchaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CaptchaId"));

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime");

                    b.HasKey("CaptchaId");

                    b.HasIndex("CarId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("DepositCaptchas");
                });

            modelBuilder.Entity("BusinessObjects.Models.MaintenanceAppointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppointmentId"));

                    b.Property<DateOnly>("AppointmentDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("AppointmentTime")
                        .HasColumnType("time");

                    b.Property<string>("CarName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("CustomerEmail")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LicensePlate")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("PackageId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pending");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("AppointmentId")
                        .HasName("PK__Maintena__8ECDFCC2C25D6E2B");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PackageId");

                    b.ToTable("MaintenanceAppointments");
                });

            modelBuilder.Entity("BusinessObjects.Models.MaintenancePackage", b =>
                {
                    b.Property<int>("PackageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PackageId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("EstimatedDuration")
                        .HasColumnType("int");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Available");

                    b.HasKey("PackageId")
                        .HasName("PK__Maintena__322035CCFD54E0FD");

                    b.ToTable("MaintenancePackages");

                    b.HasData(
                        new
                        {
                            PackageId = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Kiểm tra toàn diện 30 điểm, thay nhớt động cơ và lọc nhớt, kiểm tra hệ thống phanh và bổ sung nước làm mát. Phù hợp cho bảo dưỡng định kỳ mỗi 5.000 km.",
                            EstimatedDuration = 120,
                            PackageName = "Bảo dưỡng Tiêu chuẩn",
                            Price = 1500000m,
                            Status = "Available"
                        },
                        new
                        {
                            PackageId = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Kiểm tra hệ thống điện tử bằng máy chuyên dụng, vệ sinh buồng đốt, vệ sinh kim phun, đảo lốp, cân bằng động và thay toàn bộ chất lỏng (dầu máy, dầu phanh, nước làm mát).",
                            EstimatedDuration = 240,
                            PackageName = "Bảo dưỡng Toàn diện VIP",
                            Price = 4500000m,
                            Status = "Available"
                        },
                        new
                        {
                            PackageId = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Kiểm tra áp suất lốp, độ mòn lốp, hệ thống chiếu sáng, hệ thống phanh, gạt mưa và bình ắc quy để đảm bảo an toàn tuyệt đối cho chuyến đi dài.",
                            EstimatedDuration = 60,
                            PackageName = "Kiểm tra Xe trước Chuyến đi",
                            Price = 500000m,
                            Status = "Available"
                        });
                });

            modelBuilder.Entity("BusinessObjects.Models.Part", b =>
                {
                    b.Property<int>("PartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PartId"));

                    b.Property<string>("Brand")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PartCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PartName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Available");

                    b.HasKey("PartId")
                        .HasName("PK__Parts__7C3F0D509A440590");

                    b.HasIndex("CategoryId");

                    b.HasIndex(new[] { "PartCode" }, "UQ__Parts__6525D39D6EAC6A52")
                        .IsUnique();

                    b.ToTable("Parts");

                    b.HasData(
                        new
                        {
                            PartId = 1,
                            Brand = "Michelin",
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Lốp hiệu năng cao, bám đường cực tốt trong mọi điều kiện thời tiết.",
                            ImageUrl = "https://images.unsplash.com/photo-1578844251758-2f71da64c96f?auto=format&fit=crop&w=600&q=80",
                            PartCode = "PT-MIC-PS4",
                            PartName = "Lốp xe Michelin Pilot Sport 4",
                            Price = 3200000m,
                            Quantity = 40,
                            Status = "Available"
                        },
                        new
                        {
                            PartId = 2,
                            Brand = "GS Battery",
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ắc quy khô miễn bảo dưỡng, độ bền cao, khởi động mạnh mẽ.",
                            ImageUrl = "https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?auto=format&fit=crop&w=600&q=80",
                            PartCode = "PT-GS-12V45",
                            PartName = "Ắc quy GS 12V 45Ah",
                            Price = 1450000m,
                            Quantity = 25,
                            Status = "Available"
                        },
                        new
                        {
                            PartId = 3,
                            Brand = "Castrol",
                            CategoryId = 3,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Dầu nhớt công nghệ tổng hợp hoàn toàn bảo vệ động cơ ngay khi khởi động.",
                            ImageUrl = "https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?auto=format&fit=crop&w=600&q=80",
                            PartCode = "PT-CAS-5W30",
                            PartName = "Dầu nhớt Castrol Magnatec 5W-30",
                            Price = 850000m,
                            Quantity = 50,
                            Status = "Available"
                        },
                        new
                        {
                            PartId = 4,
                            Brand = "Bosch",
                            CategoryId = 4,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Gạt mưa cao cấp từ Bosch Đức, gạt sạch nước nhẹ nhàng, êm ái.",
                            ImageUrl = "https://images.unsplash.com/photo-1517524206127-48bbd363f3d7?auto=format&fit=crop&w=600&q=80",
                            PartCode = "PT-BOS-AERO",
                            PartName = "Gạt mưa Bosch Aerotwin",
                            Price = 450000m,
                            Quantity = 60,
                            Status = "Available"
                        },
                        new
                        {
                            PartId = 5,
                            Brand = "Philips",
                            CategoryId = 2,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Bóng đèn LED H7 siêu sáng, gom sáng tốt, độ bền lên đến 5 năm.",
                            ImageUrl = "https://images.unsplash.com/photo-1508974239320-0a029497e820?auto=format&fit=crop&w=600&q=80",
                            PartCode = "PT-PHI-LEDH7",
                            PartName = "Đèn pha LED Philips Ultinon Essential",
                            Price = 1200000m,
                            Quantity = 15,
                            Status = "Available"
                        });
                });

            modelBuilder.Entity("BusinessObjects.Models.PartCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("CategoryId")
                        .HasName("PK__PartCate__19093A0B38EB3018");

                    b.ToTable("PartCategories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Động cơ & Truyền động",
                            Description = "Các bộ phận liên quan đến động cơ, hộp số và truyền động."
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Hệ thống điện & Ắc quy",
                            Description = "Ắc quy, máy phát điện, đèn và hệ thống điện."
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Dầu nhớt & Hóa chất",
                            Description = "Dầu máy, nước làm mát, dầu phanh và hóa chất bảo dưỡng."
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Ngoại thất & Phụ kiện",
                            Description = "Lốp xe, gạt mưa, gương và các phụ kiện trang trí ngoại thất."
                        });
                });

            modelBuilder.Entity("BusinessObjects.Models.PartOrder", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("CustomerEmail")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DeliveryMethod")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pickup");

                    b.Property<string>("ShippingAddress")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("ShippingFee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pending");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("OrderId")
                        .HasName("PK__PartOrde__C3905BCF6A12AD11");

                    b.HasIndex("CustomerId");

                    b.ToTable("PartOrders");
                });

            modelBuilder.Entity("BusinessObjects.Models.PartOrderDetail", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderDetailId"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("PartId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("OrderDetailId")
                        .HasName("PK__PartOrde__D3B9D36CC532A696");

                    b.HasIndex("OrderId");

                    b.HasIndex("PartId");

                    b.ToTable("PartOrderDetails");
                });

            modelBuilder.Entity("BusinessObjects.Models.PurchaseRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestId"));

                    b.Property<string>("CaptchaCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("CustomerEmail")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("DepositAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("DepositDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DepositExpiry")
                        .HasColumnType("datetime");

                    b.Property<string>("Message")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pending");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("RequestId")
                        .HasName("PK__Purchase__33A8517AB622A517");

                    b.HasIndex("CarId");

                    b.HasIndex("CustomerId");

                    b.ToTable("PurchaseRequests");
                });

            modelBuilder.Entity("BusinessObjects.Models.AppUser", b =>
                {
                    b.HasOne("BusinessObjects.Models.AppRole", "Role")
                        .WithMany("AppUsers")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK_AppUsers_AppRoles");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("BusinessObjects.Models.Car", b =>
                {
                    b.HasOne("BusinessObjects.Models.CarBrand", "Brand")
                        .WithMany("Cars")
                        .HasForeignKey("BrandId")
                        .IsRequired()
                        .HasConstraintName("FK_Cars_CarBrands");

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("BusinessObjects.Models.DepositCaptcha", b =>
                {
                    b.HasOne("BusinessObjects.Models.Car", "Car")
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DepositCaptchas_Cars");

                    b.Navigation("Car");
                });

            modelBuilder.Entity("BusinessObjects.Models.MaintenanceAppointment", b =>
                {
                    b.HasOne("BusinessObjects.Models.AppUser", "Customer")
                        .WithMany("MaintenanceAppointments")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK_MaintenanceAppointments_AppUsers");

                    b.HasOne("BusinessObjects.Models.MaintenancePackage", "Package")
                        .WithMany("MaintenanceAppointments")
                        .HasForeignKey("PackageId")
                        .IsRequired()
                        .HasConstraintName("FK_MaintenanceAppointments_Packages");

                    b.Navigation("Customer");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("BusinessObjects.Models.Part", b =>
                {
                    b.HasOne("BusinessObjects.Models.PartCategory", "Category")
                        .WithMany("Parts")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FK_Parts_PartCategories");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BusinessObjects.Models.PartOrder", b =>
                {
                    b.HasOne("BusinessObjects.Models.AppUser", "Customer")
                        .WithMany("PartOrders")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK_PartOrders_AppUsers");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("BusinessObjects.Models.PartOrderDetail", b =>
                {
                    b.HasOne("BusinessObjects.Models.PartOrder", "Order")
                        .WithMany("PartOrderDetails")
                        .HasForeignKey("OrderId")
                        .IsRequired()
                        .HasConstraintName("FK_PartOrderDetails_PartOrders");

                    b.HasOne("BusinessObjects.Models.Part", "Part")
                        .WithMany("PartOrderDetails")
                        .HasForeignKey("PartId")
                        .IsRequired()
                        .HasConstraintName("FK_PartOrderDetails_Parts");

                    b.Navigation("Order");

                    b.Navigation("Part");
                });

            modelBuilder.Entity("BusinessObjects.Models.PurchaseRequest", b =>
                {
                    b.HasOne("BusinessObjects.Models.Car", "Car")
                        .WithMany("PurchaseRequests")
                        .HasForeignKey("CarId")
                        .IsRequired()
                        .HasConstraintName("FK_PurchaseRequests_Cars");

                    b.HasOne("BusinessObjects.Models.AppUser", "Customer")
                        .WithMany("PurchaseRequests")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK_PurchaseRequests_AppUsers");

                    b.Navigation("Car");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("BusinessObjects.Models.AppRole", b =>
                {
                    b.Navigation("AppUsers");
                });

            modelBuilder.Entity("BusinessObjects.Models.AppUser", b =>
                {
                    b.Navigation("MaintenanceAppointments");

                    b.Navigation("PartOrders");

                    b.Navigation("PurchaseRequests");
                });

            modelBuilder.Entity("BusinessObjects.Models.Car", b =>
                {
                    b.Navigation("PurchaseRequests");
                });

            modelBuilder.Entity("BusinessObjects.Models.CarBrand", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("BusinessObjects.Models.MaintenancePackage", b =>
                {
                    b.Navigation("MaintenanceAppointments");
                });

            modelBuilder.Entity("BusinessObjects.Models.Part", b =>
                {
                    b.Navigation("PartOrderDetails");
                });

            modelBuilder.Entity("BusinessObjects.Models.PartCategory", b =>
                {
                    b.Navigation("Parts");
                });

            modelBuilder.Entity("BusinessObjects.Models.PartOrder", b =>
                {
                    b.Navigation("PartOrderDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
